language: java
sudo: required

#disable Travis default install 
install: true

services:
  - mysql

branches:
  only:
    - master

before_install:
    - cd Project

before_script:

    #- mysql -e 'CREATE DATABASE db_test;'
    - cat src/test/resources/db_test_script.sql | mysql -uroot

script:
    - mvn clean install -Denv=test
