language: java
sudo: required

#disable Travis default install 
install: true

services:
  - mysql

branches:
  only:
    - master

before_install:
    - cd Project

before_script:

    - mysql < src/test/resources/db_test_script.sql -uroot 

script:
    - mvn clean install -Denv=test
